import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { createTerminal } from '@preventive/terminal'

// Each line was run by GNU coreutils 9.4, findutils 4.9 and tree 2.1.1 over
// the same tree, bound read-only at /w with a fresh /tmp, as the session's
// user: `/` is root's, so making or taking away a name in it is refused with
// EACCES, and the mount with EROFS. The answer here is the one they gave.
const SOURCES = {
  'a.txt': 'hello\n',
  "it's": 'q\n',
  'dir/g.js': 'g\n',
  'dir/sub/f.js': 'f\n',
  'dir/sub/deeper/e.txt': 'e\n',
  emptydir: { type: 'directory' },
  fslash: { type: 'symlink', target: 'a.txt/' },
  self: { type: 'symlink', target: 'self' },
  loop1: { type: 'symlink', target: 'loop2' },
  loop2: { type: 'symlink', target: 'loop1' },
  c1: { type: 'symlink', target: 'a.txt' },
  c2: { type: 'symlink', target: 'c1' },
  c3: { type: 'symlink', target: 'c2' },
  c4: { type: 'symlink', target: 'c3' },
  c5: { type: 'symlink', target: 'c4' },
  c6: { type: 'symlink', target: 'c5' },
  c7: { type: 'symlink', target: 'c6' },
  c8: { type: 'symlink', target: 'c7' },
  c9: { type: 'symlink', target: 'c8' },
  c10: { type: 'symlink', target: 'c9' },
  c11: { type: 'symlink', target: 'c10' },
  c12: { type: 'symlink', target: 'c11' },
  c13: { type: 'symlink', target: 'c12' },
  c14: { type: 'symlink', target: 'c13' },
  c15: { type: 'symlink', target: 'c14' },
  c16: { type: 'symlink', target: 'c15' },
  c17: { type: 'symlink', target: 'c16' },
  c18: { type: 'symlink', target: 'c17' },
  c19: { type: 'symlink', target: 'c18' },
  c20: { type: 'symlink', target: 'c19' },
  c21: { type: 'symlink', target: 'c20' },
  c22: { type: 'symlink', target: 'c21' },
  c23: { type: 'symlink', target: 'c22' },
  c24: { type: 'symlink', target: 'c23' },
  c25: { type: 'symlink', target: 'c24' },
  c26: { type: 'symlink', target: 'c25' },
  c27: { type: 'symlink', target: 'c26' },
  c28: { type: 'symlink', target: 'c27' },
  c29: { type: 'symlink', target: 'c28' },
  c30: { type: 'symlink', target: 'c29' },
  c31: { type: 'symlink', target: 'c30' },
  c32: { type: 'symlink', target: 'c31' },
  c33: { type: 'symlink', target: 'c32' },
  c34: { type: 'symlink', target: 'c33' },
  c35: { type: 'symlink', target: 'c34' },
  c36: { type: 'symlink', target: 'c35' },
  c37: { type: 'symlink', target: 'c36' },
  c38: { type: 'symlink', target: 'c37' },
  c39: { type: 'symlink', target: 'c38' },
  c40: { type: 'symlink', target: 'c39' },
  c41: { type: 'symlink', target: 'c40' },
  c42: { type: 'symlink', target: 'c41' },
}
const CASES = [
  ["du --apparent-size dir", "1\tdir/sub/deeper\n1\tdir/sub\n1\tdir\n", "", 0],
  ["rm -f a.txt/; echo $?", "1\n", "rm: cannot remove 'a.txt/': Read-only file system\n", 0],
  ["rm a.txt/", "", "rm: cannot remove 'a.txt/': Read-only file system\n", 1],
  ["rm -f nope; echo $?", "0\n", "", 0],
  ["rm -f nope/x; echo $?", "0\n", "", 0],
  ["rm -f a.txt/x; echo $?", "0\n", "", 0],
  ["rm -f /x; echo $?", "0\n", "", 0],
  ["rm /x", "", "rm: cannot remove '/x': No such file or directory\n", 1],
  ["rm -f /tmp/nope/; echo $?", "0\n", "", 0],
  ["touch /tmp/f; rm -f /tmp/f/; echo $?", "0\n", "", 0],
  ["touch /tmp/f; rm /tmp/f/", "", "rm: cannot remove '/tmp/f/': Not a directory\n", 1],
  ["rm -f dir/; echo $?", "1\n", "rm: cannot remove 'dir/': Is a directory\n", 0],
  ["rm -f fslash; echo $?", "1\n", "rm: cannot remove 'fslash': Read-only file system\n", 0],
  ["rm self", "", "rm: cannot remove 'self': Read-only file system\n", 1],
  ["rm -f c41", "", "rm: cannot remove 'c41': Read-only file system\n", 1],
  ["rm -r emptydir", "", "rm: cannot remove 'emptydir': Read-only file system\n", 1],
  ["rm -rv dir/sub/deeper", "", "rm: cannot remove 'dir/sub/deeper/e.txt': Read-only file system\n", 1],
  ["echo x > /tmp/a; rm -r /tmp; ls -A /tmp", "", "rm: cannot remove '/tmp': Permission denied\n", 0],
  ["mkdir -p /tmp/d/e; rm -rf /tmp; ls -A /tmp", "", "rm: cannot remove '/tmp': Permission denied\n", 0],
  ["rm -rf /", "", "rm: it is dangerous to operate recursively on '/'\nrm: use --no-preserve-root to override this failsafe\n", 1],
  ["rm -r //", "", "rm: it is dangerous to operate recursively on '//' (same as '/')\nrm: use --no-preserve-root to override this failsafe\n", 1],
  ["rm -r /tmp/..", "", "rm: refusing to remove '.' or '..' directory: skipping '/tmp/..'\n", 1],
  ["rm /", "", "rm: cannot remove '/': Is a directory\n", 1],
  ["rm -r /.", "", "rm: refusing to remove '.' or '..' directory: skipping '/.'\n", 1],
  ["rm /tmp", "", "rm: cannot remove '/tmp': Is a directory\n", 1],
  ["rm -rf /w/..", "", "rm: refusing to remove '.' or '..' directory: skipping '/w/..'\n", 1],
  ["ls fslash; echo $?", "2\n", "ls: cannot access 'fslash': Not a directory\n", 0],
  ["ls -d fslash", "fslash\n", "", 0],
  ["ls fslash/", "", "ls: cannot access 'fslash/': Not a directory\n", 2],
  ["ls self; echo $?", "self\n0\n", "", 0],
  ["ls loop1", "loop1\n", "", 0],
  ["ls c41", "c41\n", "", 0],
  ["ls c40", "c40\n", "", 0],
  ["ls -F c41", "c41@\n", "", 0],
  ["touch -; echo $?", "0\n", "", 0],
  ["touch -c -; echo $?", "0\n", "", 0],
  ["touch - >&-; echo $?", "1\n", "touch: setting times of '-': Bad file descriptor\n", 0],
  ["realpath c41", "/w/a.txt\n", "", 0],
  ["realpath c42", "/w/a.txt\n", "", 0],
  ["realpath -m c41/x", "/w/a.txt/x\n", "", 0],
  ["realpath -e c41", "/w/a.txt\n", "", 0],
  ["realpath self", "", "realpath: self: Too many levels of symbolic links\n", 1],
  ["realpath -m self/x", "/w/self/x\n", "", 0],
  ["realpath loop1", "", "realpath: loop1: Too many levels of symbolic links\n", 1],
  ["realpath -m loop1/x", "/w/loop1/x\n", "", 0],
  ["realpath -m loop1/../a.txt", "/w/a.txt\n", "", 0],
  ["realpath -e c42/", "", "realpath: c42/: Not a directory\n", 1],
  ["realpath c41/", "", "realpath: c41/: Not a directory\n", 1],
  ["realpath -s c41", "", "realpath: c41: Too many levels of symbolic links\n", 1],
  ["realpath -L c41", "", "realpath: c41: Too many levels of symbolic links\n", 1],
  ["cat c40", "hello\n", "", 0],
  ["cat c41", "", "cat: c41: Too many levels of symbolic links\n", 1],
  ["tree -L1 dir", "", "tree: Invalid level, must be greater than 0.\n", 1],
  ["tree -L 1x dir", "dir\n├── g.js\n└── sub\n\n2 directories, 1 file\n", "", 0],
  ["tree -L 0 dir", "", "tree: Invalid level, must be greater than 0.\n", 1],
  ["tree -L dir", "", "tree: Invalid level, must be greater than 0.\n", 1],
  ["tree -L 2 dir", "dir\n├── g.js\n└── sub\n    ├── deeper\n    └── f.js\n\n3 directories, 2 files\n", "", 0],
  ["tree -dL 1 dir", "dir\n└── sub\n\n2 directories\n", "", 0],
  ["mkdir dir", "", "mkdir: cannot create directory ‘dir’: File exists\n", 1],
  ["find nope", "", "find: ‘nope’: No such file or directory\n", 1],
  ["basename a b c", "", "basename: extra operand ‘c’\nTry 'basename --help' for more information.\n", 1],
  ["basename", "", "basename: missing operand\nTry 'basename --help' for more information.\n", 1],
  ["dirname", "", "dirname: missing operand\nTry 'dirname --help' for more information.\n", 1],
  ["find '' ", "", "find: ‘’: No such file or directory\n", 1],
  ["mkdir -v /tmp/n", "mkdir: created directory '/tmp/n'\n", "", 0],
  ["mkdir -pv /tmp/p/q", "mkdir: created directory '/tmp/p'\nmkdir: created directory '/tmp/p/q'\n", "", 0],
  ["ls \"it's\" nope", "it's\n", "ls: cannot access 'nope': No such file or directory\n", 2],
  ["ls 'a b'", "", "ls: cannot access 'a b': No such file or directory\n", 2],
  ["cp", "", "cp: missing file operand\nTry 'cp --help' for more information.\n", 1],
  ["rm", "", "rm: missing operand\nTry 'rm --help' for more information.\n", 1],
  ["mkdir", "", "mkdir: missing operand\nTry 'mkdir --help' for more information.\n", 1],
  ["touch", "", "touch: missing file operand\nTry 'touch --help' for more information.\n", 1],
  ["ln", "", "ln: missing file operand\nTry 'ln --help' for more information.\n", 1],
  ["realpath", "", "realpath: missing operand\nTry 'realpath --help' for more information.\n", 1],
  ["stat", "", "stat: missing operand\nTry 'stat --help' for more information.\n", 1],
  ["cp a.txt", "", "cp: missing destination file operand after 'a.txt'\nTry 'cp --help' for more information.\n", 1],
  ["ln -sT a", "", "ln: missing destination file operand after 'a'\nTry 'ln --help' for more information.\n", 1],
  ["du -sd1 dir", "", "du: warning: summarizing conflicts with --max-depth=1\nTry 'du --help' for more information.\n", 1],
  ["du -s -d 0 dir", "24\tdir\n", "du: warning: summarizing is the same as using --max-depth=0\n", 0],
  ["touch a.txt", "", "touch: cannot touch 'a.txt': Read-only file system\n", 1],
  ["touch dir", "", "touch: setting times of 'dir': Read-only file system\n", 1],
  ["touch /w", "", "touch: setting times of '/w': Read-only file system\n", 1],
  ["touch fslash", "", "touch: setting times of 'fslash': Not a directory\n", 1],
  ["touch -c a.txt", "", "touch: setting times of 'a.txt': Read-only file system\n", 1],
  ["cp a.txt /tmp/x/", "", "cp: cannot create regular file '/tmp/x/': Not a directory\n", 1],
  ["mkdir /tmp/d; cp -T a.txt /tmp/d", "", "cp: cannot overwrite directory '/tmp/d' with non-directory\n", 1],
  ["cp -n a.txt /tmp/x; echo $?", "0\n", "cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead\n", 0],
  ["mkdir /tmp/d; cp -r dir /tmp/e; cp -rT dir /tmp/d; ls /tmp/d", "g.js\nsub\n", "", 0],
  ["mkdir /x", "", "mkdir: cannot create directory ‘/x’: Permission denied\n", 1],
  ["touch /x", "", "touch: cannot touch '/x': Permission denied\n", 1],
  ["cp a.txt /x", "", "cp: cannot create regular file '/x': Permission denied\n", 1],
  ["ln -s a /x", "", "ln: failed to create symbolic link '/x': Permission denied\n", 1],
  ["mkdir -p /x/y", "", "mkdir: cannot create directory ‘/x’: Permission denied\n", 1],
  ["mkdir /w/x", "", "mkdir: cannot create directory ‘/w/x’: Read-only file system\n", 1],
  ["touch /w/x", "", "touch: cannot touch '/w/x': Read-only file system\n", 1],
  ["cp -r dir /x", "", "cp: cannot create directory '/x': Permission denied\n", 1],
  ["ln -sf a /w/a.txt", "", "ln: failed to create symbolic link '/w/a.txt': Read-only file system\n", 1],
  ["mkdir /tmp", "", "mkdir: cannot create directory ‘/tmp’: File exists\n", 1],
  ["mkdir /w", "", "mkdir: cannot create directory ‘/w’: File exists\n", 1],
  ["touch /tmp/q; ln -s q /tmp/r; mkdir /tmp/r", "", "mkdir: cannot create directory ‘/tmp/r’: File exists\n", 1],
  ["mkdir -p self", "", "mkdir: cannot stat ‘self’: Too many levels of symbolic links\n", 1],
  ["mkdir -p loop1/x", "", "mkdir: cannot create directory ‘loop1’: Too many levels of symbolic links\n", 1],
  ["mkdir -p self/x", "", "mkdir: cannot create directory ‘self’: Too many levels of symbolic links\n", 1],
  ["mkdir self", "", "mkdir: cannot create directory ‘self’: File exists\n", 1],
  ["mkdir -p c41", "", "mkdir: cannot stat ‘c41’: Too many levels of symbolic links\n", 1],
  ["mkdir -p fslash", "", "mkdir: cannot create directory ‘fslash’: File exists\n", 1],
  ["mkdir -p /tmp/d/e; find /tmp/d -name e -exec rm -r {} \\;", "", "find: ‘/tmp/d/e’: No such file or directory\n", 1],
  ["du ''", "", "du: invalid zero-length file name\n", 1],
  ["du '' dir", "8\tdir/sub/deeper\n16\tdir/sub\n24\tdir\n", "du: invalid zero-length file name\n", 1],
  ["ls -dF dir/", "dir//\n", "", 0],
  ["ls -dF dir/ emptydir", "dir//\nemptydir/\n", "", 0],
  ["mkdir -p /tmp/d/e; find /tmp/d -exec rm -r {} \\; ; echo $?", "1\n", "find: ‘/tmp/d’: No such file or directory\n", 0],
  ["touch /tmp/f; ln -s f/ /tmp/l; touch /tmp/l", "", "touch: setting times of '/tmp/l': Not a directory\n", 1],
  ["ln -s /tmp/x/ /tmp/l; touch /tmp/l; ls /tmp", "l\n", "touch: setting times of '/tmp/l': No such file or directory\n", 0],
  ["ln -s /tmp/x/ /tmp/l; tee /tmp/l < a.txt", "hello\n", "tee: /tmp/l: Is a directory\n", 1],
  ["ln -s /tmp/x/ /tmp/l; cp a.txt /tmp/l", "", "cp: not writing through dangling symlink '/tmp/l'\n", 1],
]

describe('filesystem commands answer as GNU does', () => {
  for (const [command, stdout, stderr, exitCode] of CASES) {
    it(command, async () => {
      const result = await createTerminal(SOURCES, { mount: '/w', writable: '/tmp/' }).run(command)
      assert.deepEqual([result.stdout, result.stderr, result.exitCode, result.unsupported], [stdout, stderr, exitCode, []])
    })
  }
})
