import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { createTerminal } from '@preventive/terminal'

const DYNAMIC = 'sed -n "$(grep -n \'^  on(\' a/b.txt | cut -d: -f1),+60p"'
const lines = Array.from({ length: 75 }, (_, i) => i === 6 ? '  on(event) {' : `line ${i + 1}`)
const source = lines.join('\n') + '\n'
const expected = lines.slice(6, 67).join('\n') + '\n'
const result = (stdout, exitCode = 0, stderr = '') => ({ stdout, stderr, exitCode, cwd: '/', unsupported: [] })

describe('sed ranges generated by logged grep and cut substitutions', () => {
  for (const command of [`${DYNAMIC} a/b.txt`, `${DYNAMIC} < a/b.txt`, `cat a/b.txt | ${DYNAMIC}`]) {
    it(`prints the matched line and 60 following lines: ${command}`, () => {
      assert.deepEqual(createTerminal({ 'a/b.txt': source }).run(command), result(expected))
    })
  }

  it('the exact logged command reads stdin, with no implicit file operand', () => {
    assert.deepEqual(createTerminal({ 'a/b.txt': source }).run(DYNAMIC), result(''))
  })

  it('the inner grep file does not replace the outer sed input stream', () => {
    const input = lines.map((_, i) => `input ${i + 1}`).join('\n')
    const stdout = lines.slice(6, 67).map((_, i) => `input ${i + 7}`).join('\n') + '\n'
    const terminal = createTerminal({ 'a/b.txt': source, input })
    assert.deepEqual(terminal.run(`cat input | ${DYNAMIC}`), result(stdout))
  })

  it('clips the relative endpoint at EOF and preserves an unterminated last line', () => {
    const text = 'before\n  on(event) {\nlast'
    assert.deepEqual(createTerminal({ 'a/b.txt': text }).run(`${DYNAMIC} a/b.txt`), result('  on(event) {\nlast'))
  })

  it('can select one start explicitly when grep has multiple matches', () => {
    const text = 'before\n  on(first) {\nmiddle\n  on(second) {\nlast\n'
    const command = DYNAMIC.replace('grep -n ', 'grep -n -m1 ') + ' a/b.txt'
    assert.deepEqual(createTerminal({ 'a/b.txt': text }).run(command), result(text.slice(text.indexOf('  on('))))
  })

  for (const [name, text] of [
    ['no match', 'before\nbody\nlast\n'],
    ['multiple matches', 'before\n  on(first) {\nmiddle\n  on(second) {\nlast\n'],
  ]) {
    it(`reports an ordinary malformed-script error for ${name}`, () => {
      const terminal = createTerminal({ 'a/b.txt': text })
      const actual = terminal.run(`${DYNAMIC} a/b.txt`)
      assert.equal(actual.exitCode, 1)
      assert.equal(actual.stdout, '')
      assert.match(actual.stderr, /^sed: /u)
      assert.deepEqual(actual.unsupported, [])
      assert.deepEqual(terminal.run(`${DYNAMIC} a/b.txt 2>/dev/null | cat`), result(''))
    })
  }
})

describe('logged sed regex ranges with literal parentheses and semicolons', () => {
  for (const [text, stdout] of [
    ['before\na b = call(\nbody;\n);\nafter\n', 'a b = call(\nbody;\n);\n'],
    ['a b\nbody\nlast', 'a b\nbody\nlast'],
    ['a b\n);\nignored\na b again\n); trailing\nafter\n', 'a b\n);\na b again\n); trailing\n'],
    ['before\n);\nafter\n', ''],
    ['', ''],
  ]) {
    it(`sed -n '/a b/,/^);/p' on ${JSON.stringify(text)}`, () => {
      const terminal = createTerminal({ 'file.txt': text })
      assert.deepEqual(terminal.run("sed -n '/a b/,/^);/p' file.txt"), result(stdout))
    })
  }

  it('removes blank lines from a source preview without an unsupported diagnostic', () => {
    const terminal = createTerminal({ 'README.md': '\n# Project\n \t\nDetails\n\n' })
    assert.deepEqual(terminal.run("sed '/^[[:space:]]*$/d' README.md"), result('# Project\nDetails\n'))
  })
})
